apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: cloud_test
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP